### PR TITLE
Add downloaded image to gitignore

### PR DESCRIPTION
**Pull request by wildbio**
Per #16, I added a downloaded image (wss-wu-dryville.jpg) to the .gitignore file :cactus::house:

### CODE REVIEW

**Review by jesse-ross — APPROVED** [review]
Looks good! 🚂

**Comment by wildbio** [comment]
Fantastic! Can you please merge this PR when you get a chance? :bowtie:

**Comment by jesse-ross** [comment]
Sorry, I thought I had hit the button!

**Comment by wildbio** [comment]
Great, thank you!!

**Pull request merged**
